### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by BangDori** [BangDori/FE-JavaScript-Study#1]
**JavaScript Hoisting 대해서 자신이 아는 만큼 작성해주세요.**

다음과 같이 코드와 함께 자신의 생각을 작성해도 됩니다.

```
catName("클로이");

function catName(name) {
  console.log("제 고양이의 이름은 " + name + "입니다");
}
```

호이스팅은 위 코드에서 보이는 것처럼, catName이라는 함수를 선언하기 전에 먼저 함수를 초기화하고 사용할 수 있는 것입니다.

**Comment by Tentennball** [comment]
자바스크립트 엔진은 코드를 실행하기 전 실행 컨텍스트를 위한과정에서 모든 선언(var, let, const, function, class)을 스코프에 등록한다.(실행 컨텍스트란 실행가능한 코드가 실행되기 위해 필요한 환경을 의미한다.) 호이스팅은 코드를 실행하기 전 이런 선언이 해당 스코프의 최상단으로 끌어 올려진것 같이 동작하는 현상을 말한다. 하지만 선언! 선언문에서만 호이스팅이 되고 표현식은 안된다는 것을 알자.(예시참조)
```
foo1(); // 함수 선언문이라서 호이스팅 발생.
foo2(); // 함수 표현식이라서 호이스팅 불가능.
function foo1() {
  console.log('Hello');
}
var foo2 = function() {
  console.log('world');
}
```

**Comment by BangDori** [comment]
JavaScript에서 **호이스팅**(hoisting)이란, 인터프리터가 변수와 함수의 메모리 공간을 선언 전에 미리 할당하는 것을 의미합니다. `var`로 선언한 변수의 경우 호이스팅 시 **`undefined`로 변수를 초기화** 하기 때문에,  메모리 공간에 undefined 값을 가지고 존재합니다. 반면 `let`과 `const`로 선언한 변수의 경우 호이스팅 시 **변수를 초기화하지 않기 때문에, 메모리 공간만 존재**합니다.
<br />

```
console.log(varNum); // undefined
console.log(letNum); // Uncaught ReferenceError: Cannot access 'letNum' before initialization
console.log(constNum); Uncaught ReferenceError: Cannot access 'constNum' before initialization

var varNum = 2;
let letNum = 3;
const constNum = 4;
```
<br />

위 코드는 `var`, `let`, `const`로 각각 선언한 변수들에 대해 호이스팅이 어떻게 적용되는지를 나타내는 코드입니다. 위 코드에서 `varNum`의 경우 메모리 공간에 `undefined`값이 호이스팅으로 인해 미리 할당되기 때문에 실제로 `undefined`값이 출력되는 것을 확인할 수 있습니다. 하지만, `letNum`과 `constNum`의 경우 호이스팅으로 메모리 공간은 존재하지만 값이 초기화되지 않았기 때문에, 초기화 되기 전에 접근할 수 없다는 에러가 발생하는 것을 확인할 수 있습니다.

**Comment by mingking2** [comment]
* **호이스팅**이란 함수 안에 있는 선언들을 모두 끌어올려서 해당 함수 **유효 범위의 최상단**에 선언하는 것을 말한다. 
   * **var 변수 선언**과 **함수선언문**에서만 호이스팅이 일어난다. 
   * var 변수 선언과 함수의 선언만 위로 끌어올려지며, 할당은 끌어 올려지지 않는다.

```javascript
console.log(score); // undefined
var score; // 변수 선언문
```

```javascript
hello();

function hello() { // 함수선언문
      console.log("hello world!");
}
```

**Comment by hotteok00** [comment]
선언 실행 시점과 호이스팅
-	변수 선언은 런타임 이전 단계에서 실행
-	자바스크립트 엔진은 런타임에 앞서 소스코드 평과 과정을 거친다
-	평과 과정에서 변수 선언을 포함한 모든 선언문을 소소코드에서 찾아내 먼저 실행한다
-	변수 선언문이 코드의 선두로 끌어 올려진 것처럼 동작하는 자바스크립트 고유의 특징을 변수 호이스팅이라 한다.
