### ISSUE TITLE
null vs undefined

### ISSUE THREAD

**Issue by BangDori** [BangDori/FE-JavaScript-Study#2]
**null과 undefined의 차이점에 대해 설명해주세요.**

**Comment by Tentennball** [comment]
undefined는 변수는 선언되었으나, 메모리 공간에 값이 할당되지 않았을 때 쓰레기 값을 방지하기 위해 JS엔진이 초기화하는 값이다. 하지만 null은 변수에 값이 없다는 것을 의도적으로 명시할때 사용한다.  변수가 이전에 참조하던 값을 참조하지 않는다는 의미이기도 하다.

**Comment by BangDori** [comment]
```undefined```은 **변수를 선언하고 값을 할당하지 않은 상태**이고, ```null```은 **변수를 선언하고 빈 값을 할당한 상태(빈 객체)이다**. 즉, ```undefined```는 자료형이 없는 상태이다. 따라서 ```typeof```를 통해 자료형을 확인해보면 ```null```은 ```object```로, ```undefined```는 ```undefined```가 출력되는 것을 확인할 수 있다.

```
typeof null // 'object'
typeof undefined // 'undefined'
```

**Comment by mingking2** [comment]
자바스크립트에서는 var 키워드로 변수를 선언할 때 **undefined**라는 값이 암묵적으로 할당되어 초기화 된다.
 **undefined**는 개발자가 의도적으로 할당하기 위한 값이 아니라 자바스크립트 엔진이 변수가 선언되었으나 값이 할당되지 않았을 때 변수를 초기화해주는 값이다. 
**null**은 변수에 값이 없다는 것을 의도적으로 명시하고 싶을 때 사용한다. 변수가 이전에 참조하던 값을 더 이상 참조하지 않겠다는 의미이다.

**Comment by hotteok00** [comment]
undefined은 변수를 선언하고 값을 할당하지 않은 상태, null은 변수를 선언하고 빈 값을 할당한 상태(빈 객체)
따라서 typeof를 통해 자료형을 확인해보면 null은 object로, undefined는 undefined가 출력되는 것을 확인할 수 있다.
```
typeof null // 'object'
typeof undefined // 'undefined'
null === undefined // false
null == undefined // true
null === null // true
null == null // true
!null // true
isNaN(1 + null) // false
isNaN(1 + undefined) // true
```
