### ISSUE TITLE
Variable Scope

### ISSUE THREAD

**Issue by BangDori** [BangDori/FE-JavaScript-Study#3]
Variable Scope에는 Block, Function, Global이 존재합니다.

**각 scope를 변수 선언자와 연관지어 설명해주세요.**

**Comment by hotteok00** [comment]
JS는 렉시컬 스코프 방식을 채택한다
렉시컬 스코프는 함수를 호출한 곳이 아니라 선언한 곳을 기준으로 스코프를 정하는 것을 얘기한다

Scope chain은 스코프에 따라 계층을 나누어 관리하는 방식이다.
연결방식은 일방통행으로 이루어지며 가장 낮은 단계의 스코프를 가지는 변수라면 자신이 속한 스코프에서 밖에 사용되지 않고 가장 높은 단계(Global) 변수라면 코드 전역에서 사용가능하다

Block, function scope의 구분은 var와 ES6에서 추가된 let, const에 따라 나뉜다.
var로 선언된 변수라면 function 내부 어디서든 호출이 가능하지만 let, const로 선언했다면 자신이 속한 block(조건문, 반복문) 내부에서만 사용이 가능하다

**Comment by BangDori** [comment]
## Scope
자바스크립트에서, scope는 변수의 가시성 혹은 선언된 후에 사용되어지는 방법으로 언급되어 집니다. 변수의 범위(scope)는 그 변수를 선언하기 위해 사용되어지는 키워드에 의존적입니다.

Scope에는 Global Scope, Function Scope 그리고 Block Scope로 3개의 Scope가 있습니다. ES6 이전에, JavaScript는 `var` 키워드로 Global Scope와 Function Scope만을 가질 수 있었습니다. 하지만, ES6에서 `let`과 `const`가 도입되면서 자바스크립트에서도 Block Scope가 가능해지게 되었습니다.

## Global Scope
> 함수 또는 중괄호 '{}' 외부에서 선언된 변수는 Global Scope를 가지며 동일한 Javascript 코드 내 어디에서나 액세스할 수 있습니다. `var`, `let` 그리고 const는 Global Scope를 제공합니다.

```
let carName = "Volvo";
// code here can use carName

function myFunction() {
// code here can also use carName
}
```

## Function Scope
> 함수 안에서 선언된 변수는 오직 같은 함수내에서만 사용되어질 수 있습니다. 함수의 밖에서는 `undefined` 입니다. `var`, `let` 그리고 `const`는 Function Scope를 제공합니다.

```
// code here can NOT use carName

function myFunction() {
  const carName = "Volvo";   // Function Scope

  // code here can use carName
}

// code here can NOT use carName
```

## Block Scope
> Block은 '{}'로 묶인 자바스크립트 코드의 일부입니다. 블록 내에서 선언된 변수는 해당 블록 외부에서 액세스할 수 없습니다. **이 범위는 let 및 const 키워드에 의해서만 제공됩니다. var 키워드를 사용하여 블록 내에서 변수를 선언하면 블록 범위가 없습니다.**

```
if (true) {
	var value1 = 10;
	let value2 = 20;
}

console.log(value1); // value1의 경우 Function Scope이기 때문에 {} 외부에서 참조가 가능
console.log(value2); // value2의 경우 Block Scope이기 때문에 {} 외부에서 참조 불가능
```

**Comment by Tentennball** [comment]
Variable Scope에는 Block, Function, Global이 존재합니다.

각 scope를 변수 선언자와 연관지어 설명해주세요.

스코프는 쉽게 말해 식별자의 유효범위 라고 할수 있다.
상위 스코프의 변수는 하위 스코프에서 참조할 수 있지만 하위 스코프의 변수는 상위 스코프에서 참조할 수 없다.
```
let val1 = 1;
console.log(val2); // undefined
function num(){
  let val2 = 2;
  console.log(val1);  // 1
}
```
먼저 Global Scope는 전역에 의해서 생성되는 스코프이다.
코드의 어디에서든 참조 가능하다. var, let, const 모두 전역스코프를 제공한다.

Function Scope는 지역에 의해서 생성되는 스코프이다. 지역은 함수 몸체 내부를 말한다고 해도 무관하다.
함수의 밖에서는 참조할 수 없다. 함수 몸체 내부에서만 참조 가능하다. var, let, const 모두 함수 레벨 스코프를 지원한다.

Block Scope는 코드블럭에 의해서 생성되는 스코프이다.
ES6로 넘어오면서 생긴 개념이다.
if 문, for 문, while 문, try/catch 문 등 Block내에서 선언된 변수는 코드 블록 내에서만 유효하며 코드 블록 외부에서는 참조할 수 없다.
var 키워드는 중복선언이 가능하기 때문엔 Block 스코프를 따르지 않는다. let, const만 블럭 레벨 스코프를 지원한다.

**Comment by mingking2** [comment]
**Q.** 
Variable Scope에는 Block, Function, Global이 존재합니다.
각 scope를 변수 선언자와 연관지어 설명해주세요.

---
스코프는 식별자가 유효한 범위를 말한다.
스코프의 종류는 Block, Function, Global이 있다.

- Global 스코프는 코드의 가장 바깥 영역, 전역에 의해서 생성된 스코프이다.
어디서든지 참조할 수 있다는 특징이 있다. var, let, const 키워드 모두 전역스코프를 제공한다.

지역 스코프는 해당하는 지역에서만 접근할 수 있어 지역을 벗어난 곳에서는 해당 변수에 접근이 불가하다. 크게 Function 스코프와 Block 스코프로 나뉜다.

- Function 스코프 : 함수에서 선언한 변수는 해당 함수 내에서만 접근 가능하다는 것을 의미
-var, let, const 키워드 모두 Function 스코프를 제공한다.
-> var 키워드로 선언한 변수는 오로지 함수의 코드 블럭만을 지역 스코프로 인정한다.

- Block 스코프 : 블록( **{ }** ) 내부에서 선언된 변수는 해당 블록에서만 접근 가능하다는 것을 의미
var 키워드는 중복선언이 가능하기 때문에 Block 스코프를 따르지 않고 let, const 키워드만 따른다.
