### ISSUE TITLE
Programming Paradigm

### ISSUE THREAD

**Issue by BangDori** [BangDori/FE-JavaScript-Study#4]
## 패러다임(Paradigm)
> 한 시대의 사람들의 견해나 사고를 근본적으로 규정하고 있는 인식의 체계 또는 사물에 대한 이론적인 틀이나 체계. 즉, 일종의 '틀'

## 프로그래밍 패러다임의 변화

프로그래밍 패러다임이라 하면 주로 3가지를 의미합니다.
- **절차적 프로그래밍** (PP, Procedure Programming)
- **객체지향 프로그래밍** (OOP, Object Oriented Programming)
- **함수형 프로그래밍** (FP, Functional Programming)

각 패러다임들은 프로그래밍 분야에서 순서대로 인기가 있었습니다.
- 하지만, 등장 순서는 정 반대로, **함수형 -> 객체지향 -> 절차적** 순서 입니다.

## 프로그래밍 패러다임의 분류
위 3가지 주요 프로그래밍 패러다임은 [방법/목적]에 따라 분류됩니다.

1. 선언형 프로그래밍(Declearative Programming)
   - 절차형, 객체지향적 프로그래밍

2. 명령형 프로그래밍(Imperative Programming)
   - 함수형, 논리형 프로그래밍

![Programming Paradigm](https://user-images.githubusercontent.com/44726494/227571725-8f8c7610-3539-4ac4-83cc-03301a8eb2c2.jpg)

## Quiz
1. 명령형 프로그래밍 vs 선언형 프로그래밍 차이 설명
2. 프로그래밍 패러다임 3가지 중 하나를 선택해 설명

**Comment by hotteok00** [comment]
## By_chatGPT

### 1. 명령형 프로그래밍 vs 선언형 프로그래밍 차이 설명
> 명령형 프로그래밍은 프로그래머가 컴퓨터가 특정 작업을 수행하는 방법을 단계별로 지정하는 프로그래밍 패러다임입니다. 반면에 선언형 프로그래밍은 프로그래머가 프로그램에서 원하는 작업을 지정하고 컴퓨터가 이를 수행하는 방법을 알아내는 프로그래밍 패러다임입니다.

명령형 프로그래밍에서 프로그래머는 컴퓨터가 문제를 해결하기 위해 수행할 정확한 단계 순서를 지정합니다. 이는 종종 변수에 값을 할당하고, 데이터 구조를 수정하고, 실행 흐름을 제어하는 ​​명령문을 통해 수행됩니다. 코드는 기본 하드웨어와 매우 유사한 방식으로 작성되며 종종 매우 절차적입니다.
선언 프로그래밍에서 프로그래머는 프로그램이 해당 출력을 생성하는 방법을 반드시 지정하지 않고 프로그램의 출력이 무엇인지 지정합니다. 코드는 단계의 절차적 순서가 아니라 입력과 출력 사이의 관계를 설명하는 일련의 규칙 또는 제약 조건처럼 작성됩니다.

### 2. 프로그래밍 패러다임 3가지 중 하나를 선택해 설명
> 함수형 프로그래밍은 함수를 사용하여 문제를 해결하는 것을 강조하는 프로그래밍 패러다임입니다. 함수형 프로그래밍에서 함수는 일급 시민으로 취급됩니다. 즉, 값으로 전달되고 변수에 저장되며 다른 함수의 결과로 반환될 수 있습니다. 이를 통해 코드의 강력한 추상화 및 모듈화가 가능합니다.

함수형 프로그래밍의 주요 측면 중 하나는 불변성입니다. 즉, 한번 생성된 값은 변경할 수 없습니다. 대신 함수를 통해 이전 값에서 새 값이 생성됩니다. 이렇게 하면 코드에 대해 더 쉽게 추론하고 버그를 피할 수 있습니다.
함수형 프로그래밍의 또 다른 측면은 부작용이 없다는 것입니다. 즉, 함수는 자신의 범위 밖의 상태를 수정하지 말고 대신 새 값을 반환해야 합니다. 이렇게 하면 코드의 동작에 대해 더 쉽게 추론하고 테스트할 수 있습니다.
전반적으로 함수형 프로그래밍은 특히 병렬 또는 분산 시스템에서 복잡한 문제를 해결하는 데 매우 강력할 수 있습니다.



## By_googling

> 명령형(절차적) 프로그래밍은 당신이 어떤 일을 어떻게 할 것인가에 관한 것이고,
선언적 프로그래밍은 당신이 무엇을 할 것인가에 관한 것입니다.
> 선언형 방식이 제대로 동작하기 위해서는 명령형으로 "어떻게"가 구현된 것들이 추상화되어 있어야 합니다.

미리 추상화된 내용을 가지고 있는 함수나 객체들의 내부에는 결국 그 내용을 추상화하기 위한 '명령적 추상화'가 존재해야 한다.

**Comment by Tentennball** [comment]
### 1. 명령형 프로그래밍 vs 선언형 프로그래밍의 차이
명령형 프로그래밍은 어떻게 그것을 해결할 것인가에 관심이 있다.
선언형 프로그램은 프로그램이 무엇을 해야 할지에 관심이 있다.
<details><summary>예시</summary>
<p>
명령형 방식 : "저기 창가 쪽 자리가 비었네요. 저 자리로 걸어가서 앉을게요"<br>
선언형 방식 : "두 명 앉을 자리 부탁해요"<br>
명령형은 내가 자리를 어떻게 앉을 것이지에 대해서, 선언형은 어떤 것을 원하는지를 말했다.
</p>
</details> 

코드로도 예시를 들어보자.
```
// 명령형 방식
function double (arr) {
  let results = [];
  for (let i = 0; i < arr.length; i++){
    results.push(arr[i] * 2);
  }
  return results;
}

// 선언형 방식
function double(arr) {
  return arr.map((item) => item * 2);
}
```
두 함수는 배열을 파라미터로 받아 각 요소들의 값에 2를 곱하는 같은 기능을 한다. 

명령형 방식을 보면 **어떻게 배열의 요소들에 2를 곱할지 설명**하는 식(results 배열을 선언하고 for문을 써서 .....이렇게 해서 배열의 각 요소들에 2를 곱할거에요)으로 작성됐다. 

하지만 선언형 방식은 **어떻게 보다 무엇을 할 지**(요소들마다 2를 곱해주세요)만 작성됐다.
JS에 내장된 map 기능을 쓰긴 했지만 개발자는 map의 내부가 어떻게 되어있는지 몰라도 신경 쓸 필요가 없다. 
요소들마다 2를 곱하는것을 원하는데 이 기능을 하는 메서드가 map이다 라는 점만 알면 되는 것이다.

이러한 선언형 프로그래밍에 속하는 대표적인 프로그래밍 방식이 함수형 프로그래밍이고,
명령형 프로그래밍 방식은 절차형, 객체지향형 프로그래밍이다.

### 2. 프로그래밍 패러다임 중 하나를 선택해 설명 (절차형 프로그래밍)
절차적 프로그래밍이란 순차적인 처리가 중요시 되며 프로그램 전체가 유기적으로 연결되도록 만드는 프로그래밍 기법이다.

장점으로는 컴퓨터의 처리방식과 유사하기 때문에 속도가 빠르고, 모듈 구성이 용이하고 구조적인 프로그래밍이 가능하다.
단점으로는 유지보수가 어렵고, 프로그램 전체가 유기적으로 연결되어 있기 때문에 새로운 데이터나 기능을 추가하기가 어렵다.

소프트웨어의 규모가 작거나 프로젝트의 규모가 작을 때 이 방식을 채택하면 효과적이다.

**Comment by mingking2** [comment]
###  1. 명령형 프로그래밍 vs 선언형 프로그래밍 차이 설명
명령형 프로그래밍은 컴퓨터에게 어떻게 작업을 수행할지 명령하는 것이다. 즉, 프로그래머는 컴퓨터가 수행할 단계적인 지시문을 작성한다. 이 지시문은 일반적으로 변수의 값을 변경하는 반복문과 조건문, 그리고 함수를 호출하는 방식을 작성된다.

선언형 프로그래밍은 어떤 작업을 수행할지 설명하는 것이다. 즉, 프로그래머는 결과를 얻기 위해 어떤 규칙이나 제약조건을 정의한다. 이러한 규칙은 일반적으로 수학적인 공식, 논리적인 제약조건, 또는 데이터베이스에서 검색조건과 유사하다.

두 패러다임의 차이점
- 명령형 : 알고리즘은 명시하고 목표는 명시하지 않는다.
- 선언형 : 목표를 명시하고 알고리즘을 명시하지 않는다.

명령형은 HOW(어떻게 할 것인지를 설명한다), 선언형은 WHAT(무엇을 할 것인가 정의한다)의 개념이다. 그렇기 때문에 선언형에서는 구체적인 문제 해결 방법이 나와 있지 않다.

### 2. 프로그래밍 패러다임 중 하나를 선택해 설명 (객체지향 프로그래밍)
객체 지향 프로그래밍은 프로그래밍 패러다임 중 하나로, 현실 세계의 객체(Object)와 그 객체들 간의 상호작용을 모델링하여 프로그램을 구현하는 방법이다.

객체는 데이터와 해당 데이터를 조작하는 메서드(Method)를 함께 묶어 놓은 것이다. 즉, 객체는 데이터의 속성과 해당 데이터를 처리하기 위한 동작을 한 단위로 묶은 것이다. 이러한 객체들 간에는 상호작용이 발생할 수 있으며, 이를 통해 복잡한 문제를 해결할 수 있다.

객체 지향 프로그래밍에서는 객체를 기반으로 프로그램을 설계하며, 다음과 같은 개념들을 중심으로 프로그래밍이 이루어진다.

캡슐화(Encapsulation): 데이터와 메서드를 하나의 객체 안에 묶어 은닉화한다. 객체의 내부 상태를 직접 접근하지 못하게 하여 객체를 보호하고, 객체 간의 결합도를 낮추어 유지 보수성을 향상시킨다.

상속(Inheritance): 부모 클래스의 특징을 자식 클래스가 물려받는 것으로, 자식 클래스는 부모 클래스의 특징을 그대로 물려받으며, 추가로 자신의 특징을 추가할 수 있다. 이를 통해 코드의 재사용성과 유지보수성을 높일 수 있다.

다형성(Polymorphism): 같은 이름의 메서드나 연산자가 서로 다른 기능을 수행할 수 있는 것을 의미한다. 이를 통해 코드의 가독성과 유연성을 높일 수 있다.
