### ISSUE TITLE
Function?

### ISSUE THREAD

**Issue by BangDori** [BangDori/FE-JavaScript-Study#5]
**Q1) 일반 함수와 화살표 함수의 차이에 대해 설명해주세요.**
  - Q1-1) 일반 함수가 더 유용한 상황에 대한 예시를 포함해주세요.
  - Q1-2) 화살표 함수가 더 유용한 상황에 대한 예시를 포함해주세요.

**Q2) 일반 함수와 익명 함수의 차이에 대해 설명해주세요.**
  - Q2-1) 일반 함수와 익명 함수의 코드 예시를 포함해주세요.

**Comment by hotteok00** [comment]
일반 함수와 화살표 함수의 차이
=============

일반 함수와 화살표 함수의 차이점은 크게 

1. this
2. 생성자 함수 가능 여부
3. argument 사용 가능 여부

위 세가지로 나뉜다.

## this
### 일반 함수
일반 함수는 실행 될 때 마다 함수 내부에 this라는 객체가 추가된다. 이 키워드를 사용하여 함수를 호출한 개체를 참조할 수 있다. 다음은 일반 함수에서 this가 바인딩 되는 방식이다.

1. 함수 실행시에는 전역(window) 객체를 가리킨다.
2. 메소드 실행시에는 메소드를 소유하고 있는 객체를 가리킨다.
3. 생성자 실행시에는 새롭게 만들어진 객체를 가리킨다.

다시 말하면, 일반함수는 함수 선언 시에 this에 바인딩 할 객체를 정적으로 정하는 것이 아니라, 함수가 어떻게 호출 되었는지에 따라 this에 바인딩할 객체가 동적으로 결정된다. 

### 화살표 함수
화살표 함수는 this에 바인딩 할 객체가 정적으로 결정된다.  자신의 this 값을 바인딩하지 않고 화살표 함수를 둘러싼 코드의 this 값을 참조 한다. 따라서, 자신의 상위 scope의 this를 가리킨다.


## 생성자 함수 가능 여부
생성자 함수로 사용하려면 함수가 다음 조건을 충족해야 한다.

1. 함수는 function 키워드를 사용하여 정의해야 한다.
2. 새 객체를 생성하려면 new 키워드를 사용하여 함수를 호출해야 한다.
3. 함수는 this 키워드를 사용하여 개체의 속성과 메서드를 정의해야 한다.
4. 함수는 생성자 함수임을 나타내기 위해 첫 문자가 대문자여야 한다.

또한 생성자 함수를 이용하면 동일한 프로퍼티를 갖는 객체를 생성할 수 있다. 즉, 객체 생성에 필요한 prototype 프로퍼티를 가지고 있다. 이러한 이유를 생각해 볼 때,

### 일반 함수
일반 함수는 생성자 함수로 사용할 수 있다.

### 화살표 함수
화살표 함수는 생성자 함수로 사용할 수 없다. 


## argument 사용 가능 여부
### 일반 함수
일반 함수 에서는 함수가 실행 될때 암묵적으로 arguments 변수가 전달되어 사용할 수 있다.

### 화살표 함수
화살표 함수에서는 암묵적으로는 arguments 변수가 전달되지 않는다.


#### Q1-1) 일반 함수가 더 유용한 상황에 대한 예시를 포함해주세요.
```Javascript
function RegularFunc() { 
  return 'Hi'; 
}
const obj = new RegularFunc();
```
생성자 함수로 사용이 가능하다.

#### Q1-2) 화살표 함수가 더 유용한 상황에 대한 예시를 포함해주세요.
```Javascript
function addFunc(x, y) { return x + y; };
let addFunc = (x, y) => {return x + y};
```
더 짧고 간단한 코드로 동일한 결과를 얻을 수 있다.



일반 함수와 익명 함수의 차이
=============

### 일반함수
JS의 호이스팅의 영향을 받는다. 따라서 위치 상관없이 호출이 가능하다.

### 익명함수
일반 함수와 달리 이름이 존재하지 않는다. 재사용하지 않는, 한번만 사용할 함수이다. 리터럴 방식으로 변수에 담겨 사용되는 방식이다. 
```Javascript
const sayHello = function() {
  console.log("hello!");
}
sayHello(); 
```
또 호이스팅의 영향을 받지 않아서 호출 위치보다 선언부가 위에 존재해야 한다.

**Comment by Tentennball** [comment]
### 일반함수와 화살표함수
1) 일반함수
- 일반적으로 함수를 호출할 경우 global 객체를 가리킨다(기본적으로 window 객체)
```
const obj = {
  name:'이태훈',
  method() {
    console.log(this.name); // 이태훈
  }
};
```

2) 화살표함수
화살표 함수 내에서 자체적으로 가리키는 this가 없다.
상위 스코프의 this를 가리킨다.
```
let myObj = { 
    age: 30, 
    arrowFunc:() => { 
        console.log(this.age); 
    },
    regularFunc(){ 
        console.log(this.age); 
    } 
};
myObj.arrowFunc(); //undefined
myObj.regularFun(); //30
```
화살표 함수의 this를 모른다면 기대하는 값은 30이지만 결과는 undefined 이다.
화살표함수의 상위 스코프는 현재 myObj 객체가 아니라 **상위스코프인 window 객체**이기 때문이다.
일반함수에서는 arguments의 사용이 가능하다

### 일반함수가 유용한 경우
일반 함수 에서는 함수가 실행 될때 암묵적으로 arguments 변수가 전달되어 사용할 수 있다.
```
function regularFunc() {
  console.log(arguments,arguments[0]); //[1,2,3],1
}
regularFunc(1,2,3)
```

- 화살표함수에서 사용할 경우 에러가 난다.
```
const arrFunc = () => {
  console.log(arguments,arguments[0]); //arguments is not defined
}
arrFunc(1,2,3)
```
하지만 화살표 함수에서 rest 파라미터를 사용하면 arguments 사용이 가능하다
```
const arrFunc = (...args) => {
  console.log(...args); //[1,2,3]
}
arrFunc(1,2,3)
```
...이 rest 파라미
### 화살표함수가 유용한 경우
```
const fullNames5 = names.map(() => `Cool Bos`);
console.log(fullNames5)
```
위와 같이 짧고 간결하게 코드를 작성할 수 있다. 일반함수로 작성했다면 더 긴 코드가 필요했을 것이다.

### 일반함수와 익명함수의 차이
- 일반함수
JS의 호이스팅의 영향을 받기 때문에 위치에 상관없이 호출이 가능하다.
- 익명함수
이름이 존재하지 않으며, 재사용되지 않는다. 화살표 함수는 항상 익명 함수이다. 변수에 할당한다면 가능하다.
```
const sayMyName = (name) => {alert(`Hello ${name}!`)}
sayMyName('Wes');
```
단 호이스팅의 영향을 받지 않으므로 호출하는 부분보다 위에서 선언되어야 한다.

**Comment by mingking2** [comment]
# 일반함수와 화살표함수의 차이

```
function fun() { // 일반함수
  ...
}

const arrFun = () => { // 화살표 함수
  ...
};
```
## this
자바스크립트에서 모든 함수는 실행될 때마다 함수 내부에 this라는 객체가 추가된다.

 - 일반함수
    - 함수를 선언할 때 this에 바인딩할 객체가 정적으로 결정되는 것이 아니고,
    - 함수를 호출할 때 함수가 어떻게 호출되었는지에 따라 this에 바인딩할 객체가 동적으로 결정된다.
 
 - 화살표함수
   - 함수를 선언할 때 this에 바인딩할 객체가 정적으로 결정된다.
   - 화살표 함수의 this 언제나 상위 스코프의 this를 가리킨다.(Lexical this)
   - call, apply, bind 메소드를 사용하여 this를 변경할 수 없다.

## 생성자 함수로 사용 여부

 - 일반함수
   - 생성자 함수로 사용할 수 있다.
 - 화살표함수
   - prototype 프로퍼티가 없기 때문에 생성자 함수로 사용할 수 없다.

## arguments 사용 가능 여부

 - 일반함수
    - 함수가 실행될 때 암묵적으로 arguments 변수가 전달되어 사용할 수 있다.
 - 화살표함수
    - arguments 변수가 전달되지 않는다.

**Comment by mingking2** [comment]
# 일반함수와 화살표함수의 차이

```javascript
function fun() { // 일반함수
  ...
}

const arrFun = () => { // 화살표 함수
  ...
};
```
## this
자바스크립트에서 모든 함수는 실행될 때마다 함수 내부에 this라는 객체가 추가된다.

 - 일반함수
    - 함수를 선언할 때 this에 바인딩할 객체가 정적으로 결정되는 것이 아니고,
    - 함수를 호출할 때 함수가 어떻게 호출되었는지에 따라 this에 바인딩할 객체가 동적으로 결정된다.
 
 - 화살표함수
   - 함수를 선언할 때 this에 바인딩할 객체가 정적으로 결정된다.
   - 화살표 함수의 this 언제나 상위 스코프의 this를 가리킨다.(Lexical this)
   - call, apply, bind 메소드를 사용하여 this를 변경할 수 없다.

## 생성자 함수로 사용 여부

 - 일반함수
   - 생성자 함수로 사용할 수 있다.
 - 화살표함수
   - prototype 프로퍼티가 없기 때문에 생성자 함수로 사용할 수 없다.

## arguments 사용 가능 여부

 - 일반함수
    - 함수가 실행될 때 암묵적으로 arguments 변수가 전달되어 사용할 수 있다.
 - 화살표함수
    - arguments 변수가 전달되지 않는다.

### Q1-1) 일반 함수가 더 유용한 상황에 대한 예시를 포함해주세요.
```javascript
function com() {
  console.log(arguments); // Arguments(3) [1, 2, 3, callee: ƒ, Symbol(Symbol.iterator): ƒ]
}

com(1, 2, 3);
```
 -> 일반함수에서는 arguments를 사용할 수 있지만 화살표함수는 불가능하다.

### Q1-2) 화살표 함수가 더 유용한 상황에 대한 예시를 포함해주세요.

```javascript
function square(x) {
  return x * x;
}
```

```javascript
const square = x => x * x;
```

-> 화살표함수가 일반함수보다 함수 선언을 간단하고 간결하게 만들 수 있다.

# 일반함수와 익명함수의 차이

## 일반 함수

- 함수에 이름이 지정된다
- 함수를 선언하고, 해당 함수를 나중에 호출할 수 있다.
- 함수의 이름을 사용하여 재귀 호출이나 다른 곳에서 함수를 참조할 수 있다.
- 일반 함수는 `function` 키워드를 사용하여 정의된다.

예시:
```javascript
function add(a, b) {
  return a + b;
}
```

## 익명 함수
- 함수에 이름이 없다.
- 주로 다른 함수의 인자로 전달되거나, 변수에 할당되어 사용된다.
- 익명 함수는 함수 표현식으로 정의되며, 변수에 함수를 할당하는 방식으로 사용된다.

예시:

```javascript
const square = function(x) {
  return x * x;
};
```

익명 함수는 함수 표현식으로 사용되는 경우에 유용하며, 코드의 가독성과 유연성을 높일 수 있다. 예를 들어, 콜백 함수로 사용되거나, 즉시 호출되는 함수 등에서 익명 함수가 자주 사용된다.
